### PR TITLE
Update Travis CI to use standard test script.

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
Is there still a need to test with go 1.6?

**Comment by kevina** [comment]
Nevermind I am assuming that is outdated code.

New question: Is there a reason to still use `tip` which is the latest devel version and not just go 1.9?

**Comment by Stebalien** [comment]
> New question: Is there a reason to still use tip which is the latest devel version and not just go 1.9?

It allows us to catch upstream bugs/changes early. We don't do it all over the place but this package runs *all* of our smux tests.

**Comment by kevina** [comment]
> It allows us to catch upstream bugs/changes early. We don't do it all over the place but this package runs all of our smux tests.

Okay I will use both `tip` and `1.9.x` then.

**Comment by kevina** [comment]
Note `suit_test.go` is failing and not sure the best way to fix it...

**Comment by Stebalien** [comment]
@kevina I'm looking into that.

**Comment by Stebalien** [comment]
Fixing this by removing the tests. Continuing in #24.

**Pull request closed without merging**
